### PR TITLE
Support for django 1.11

### PR DESCRIPTION
**Pull request by whyscream**

### CODE REVIEW

**Comment by maerteijn** [comment]
Thank you!

I already tested this in this branch: https://github.com/django-oscar/django-oscar-api/tree/feature/test-with-oscar-1.5

So with the travis setup it works, because it will do an explicit install of a specific version of oscar before installing oscar-api.

However, when you do a completely clean install of `django-oscar-api` you get this:
```
(feature/test-with-oscar-1.5)$ python setup.py develop
...
Installed /Users/martijn/.virtualenvs/delme/lib/python2.7/site-packages/djangorestframework-3.6.4-py2.7.egg
error: Django 1.11.5 is installed but Django<1.11 is required by set(['django-haystack'])
```

This is because the official release of `django-haystack`  (<1.7) which is pinned in `django-oscar` does not support Django 1.11 

I will file a ticket with `django-oscar` soon.

**Comment by whyscream** [comment]
I created a PR for the issue in haystack: https://github.com/django-haystack/django-haystack/pull/1555

**Comment by specialunderwear** [comment]
Held

**Comment by maerteijn** [comment]
See #109 (already merged and released)

**Pull request closed without merging**
