### PR TITLE
Fix some `django 1.10` incompatibilities.

### PR DESCRIPTION
**Pull request by SalahAdDin**

### CODE REVIEW

**Comment by maerteijn** [comment]
Hi SalahAdDin,

Note that all the tests fail due to that ``def add_voucher`` does not exist. converted this to a class based view in 7092585d5ff438d4ce211794cdaecf01ee040e2b.

**Comment by SalahAdDin** [comment]
@maerteijn Can you reworks this an make a pr please¡

**Comment by SalahAdDin** [comment]
Ok man, but, the problem is that the lastes pypi version isn't the current github master branch version.

**Comment by maerteijn** [comment]
I don't understand what you mean, can you explain a bit more?

**Comment by SalahAdDin** [comment]
Pypi package installed is outdated with respect this repository!

**Comment by maerteijn** [comment]
Yes off course. Released versions are not automatically synced with a github repository. So for fixes you need to install django-oscar-api from source and not from pypi

**Comment by SalahAdDin** [comment]
Yes, i did, and make changes. Now you can pull this small fixes.

**Pull request merged**
