### PR TITLE
Added a basketmiddleware that solves the problem of mixing regular oscar

### PR DESCRIPTION
**Pull request by specialunderwear**
views with api views.

### CODE REVIEW

**Comment by jakobholmelund** [comment]
I'll give it a spin right away.. !

**Comment by jakobholmelund** [comment]
It seems not to be working :/

**Comment by specialunderwear** [comment]
can I see your middleware configuration?

**Comment by jakobholmelund** [comment]
MIDDLEWARE_CLASSES = (
    'opbeat.contrib.django.middleware.OpbeatAPMMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'oscarapi.middleware.HeaderSessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'sonofatailor.middleware.BasketMiddleware',
    'oscarapi.middleware.ApiBasketMiddleWare',
    'django.contrib.flatpages.middleware.FlatpageFallbackMiddleware',
    'impersonate.middleware.ImpersonateMiddleware'
#    'oscar_impersonate.middleware.OscarImpersonateMiddleware',
)

**Comment by specialunderwear** [comment]
Ok thanks for testing, your middleware config is correct.

**Comment by jakobholmelund** [comment]
I'm using this middleware which seems to be working, but it's kind of hacky

```
class BasketMiddleware(CoreBasketMiddleware):
    """
    Here we manage the basket in session so that it will work for both api and browser

    Following steps will be taken
    1. Check for OPEN basket in session, if found use the same.
    2. If user is authenticated, merge session basket and remove the basket from session

    """

    def get_basket(self, request):
        """
        Return the open basket for this request
        """
        if request._basket_cache is not None:
            return request._basket_cache

        # get anonymous basket before actual basket
        # else operations.prepare will overwrite the session basket with user basket
        anonymous_basket = operations.get_anonymous_basket(request)

        basket = operations.get_basket(request, True)

        # since the operations.get_basket doesnt merge the
        # anonymous basket with user basket, we need to check and merge here
        if request.user and request.user.is_authenticated():
            if anonymous_basket and anonymous_basket.id != basket.id:
                self.merge_baskets(basket, anonymous_basket)

        return basket

    def process_response(self, request, response):
        return response

    def merge_baskets(self, merge_to, merge_from):
        merge_baskets(merge_to, merge_from, add_quantities=False)
```

**Comment by specialunderwear** [comment]
Ok, what I am trying to do is get the basket stored in the cookie and then store it in the session as well, which should make baskets for anonymous users created by the oscar frontend available to the api.

So I must have missed something ...

**Comment by jakobholmelund** [comment]
Well. The problem for me seems to be that baskets created by the api isn't available without using the API. So when i go to checkout

```
def check_basket_is_not_empty(self, request):
        logger.info(request.basket)
        if request.basket.is_empty:
            raise exceptions.FailedPreCondition(
                url=reverse('basket:summary'),
                message=_(
                    "You need to add some items to your basket to checkout")
```

finds an empty basket

**Comment by specialunderwear** [comment]
ah!

That means I need to do it the other way around as well, and store the basket id from the session in the cookie.

> On 30 okt. 2015, at 14:59, Jakob Holmelund <notifications@github.com> wrote:
> 
> Well. The problem for me seems to be that baskets created by the api isn't available without using the API. So when i go to checkout
> 
> def check_basket_is_not_empty(self, request):
>         logger.info(request.basket)
>         if request.basket.is_empty:
>             raise exceptions.FailedPreCondition(
>                 url=reverse('basket:summary'),
>                 message=_(
>                     "You need to add some items to your basket to checkout")
> 
> finds an empty basket
> 
> —
> Reply to this email directly or view it on GitHub.
> 

PermanentMarkers
kvk 09170823
tel 020-8943173
mob 06-24352007
lars@permanentmarkers.nl

**Comment by jakobholmelund** [comment]
Sounds about right :) my Middleware uses that basket cache which is actually a really bad idea if you run more than one frontend instance..

**Comment by jakobholmelund** [comment]
I tried to finish it up.. Seems to be working for me, but i want to make sure i'm not doing anything unsafe..

```
class ApiBasketMiddleWare(BasketMiddleware, IsApiRequest):
    """
    Use this middleware instead of Oscar's basket middleware if you
    want to mix the api with and regular oscar views.

    Oscar uses the session to store baskets for anynymous users, but
    oscarapi can not do that, because we don't want to put the burden
    of managing a cookie jar on oscarapi clients that are not websites.
    """
    def process_request(self, request):
        #logger.info(BasketMiddleware)
        super(ApiBasketMiddleWare, self).process_request(request)

        if self.is_api_request(request):
            # we should make sure that any cookie baskets are turned into
            # session baskets, since oscarapi uses only baskets from the
            # session.
            cookie_key = self.get_cookie_key(request)
            basket = self.get_cookie_basket(
                cookie_key,
                request,
                Exception("get_cookie_basket doesn't use the manager argument")
            )
            if basket is not None:
                if request_contains_basket(request, basket):
                    pass
                else:
                    store_basket_in_session(basket, self.request.session)
        else:
            basket_id = get_basket_id_from_session(request)
            cookie_key = self.get_cookie_key(request)

            basket = Basket.objects.get(pk=basket_id,
                                            status=Basket.OPEN)

            if basket is not None:
                request.COOKIES[cookie_key] = self.get_basket_hash(basket.id)
```

**Comment by specialunderwear** [comment]
no that will definately not work out. Just use operations.get_basket to get the basket from the request. The query you are doing will raise and exception if that object doesn't exit.

But I need to look into what happens in super.process_request to see if an implementation as you are showing is sufficient.

**Comment by jakobholmelund** [comment]
Fixed that.. Seems to work. I'll report if it has any problems.

**Comment by specialunderwear** [comment]
Hi @jakobholmelund could you please test my latest revision?
I changed it so baskets altered or created by oscarapi are stored in the cookie at the end of the request.
Almost the same as your implementation but a little later, in case a basket is being merged or changed by oscarapi.

**Comment by specialunderwear** [comment]
Psst, @jakobholmelund, could you please test, for the last time?

**Comment by specialunderwear** [comment]
btw this fixes #13

**Comment by jakobholmelund** [comment]
Seems to be working. I've had it running in production the last week, and i haven't received any complaints nor have i run into bugs myself.

**Comment by jakobholmelund** [comment]
hmm Just ran into some problems.. Somehow it seems that the basket is not saved on the request object for anonymouse users.. ! so this actually doesn't work !

**Comment by specialunderwear** [comment]
hi in the latest oscar api and also in oscar Applicator has moved to offers/applicator.py instead utils/applicator.py. If you used to override it, you need to change your code. Does that help?

**Comment by jakobholmelund** [comment]
hmm i actually run my own fork of both oscar core and oscar api, so shouldn't be a problem, even though i can't be a 100% sure.. But.. I can't really see how this would be connected.. For me the problem is that get_basket from django-oscar core BasketMiddleWare doesn't return the basket for anonymous users. I have to override the get_basket method to get things to work.. I might be that it has been fixed and i just haven't merged it. I think i have to do a proper cleaning soon and align with the core branches again, that being said, this seems to work for me.. 

'''
def get_basket(self, request):
        #oscar_basket = super(ApiBasketMiddleWare, self).get_basket(request)

        #if not basket:
        # if request._basket_cache is not None:
        #     logger.info("BaSKET CACHE FOUND")
        #     return request._basket_cache

        anonymous_basket = operations.get_anonymous_basket(request)
        basket = operations.get_basket(request, True)

        # since the operations.get_basket doesnt merge the
        # anonymous basket with user basket, we need to check and merge here
        if request.user and request.user.is_authenticated():
            if anonymous_basket and anonymous_basket.id != basket.id:
                self.merge_baskets(basket, anonymous_basket)

        return basket
'''

**Comment by jakobholmelund** [comment]
Oh.. And i forgot to mention.. It works for API calls.. My problem is actually that request.basket is empty on the checkout page, so validation fails and the request get's redirected to the basket..

**Comment by specialunderwear** [comment]
I can not see how that should happen, are your users logged in or anonymous.

**Comment by albertojacini** [comment]
Hi everybody and many thanks for the amazing work,
I'm trying to make this work but I have the same problem as @jakobholmelund, the anonymous cart created by the API doesn't get attached to response.cookies and I can't find it when loading a server rendered page.
I'm surely missing something, but I found that the problem is when running super.process_response.
```
    def process_response(self, request, response):
        ...
        # Check if we need to set a cookie. If the cookies is already available
        # but is set in the cookies_to_delete list then we need to re-set it.
        has_basket_cookie = (
            cookie_key in request.COOKIES
            and cookie_key not in cookies_to_delete)

        # If a basket has had products added to it, but the user is anonymous
        # then we need to assign it to a cookie
        if (request.basket.id and not request.user.is_authenticated()
                and not has_basket_cookie):
        ...
```
I don't understand exactly what the has_basket_cookie is for. Since ApiBasketMiddleWare just added cookie_key in request.COOKIES, the last lines are not run and the cookie is not attached to response.
I kind of fixed the problem by patching ApiBasketMiddleWare this (not very clean) way:

```
    def process_response(self, request, response):
        if self.is_api_request(request) and hasattr(request, 'user'):
            # at this point we are sure a basket can be found in the session,
            # because it is enforced in process_request.
            # We just have to make sure it is stored as a cookie, because it
            # could have been created by oscarapi.
            cookie_key = self.get_cookie_key(request)  # Oscar default is 'oscar_open_basket'
            basket = get_basket(request)
            cookie = self.get_basket_hash(basket.id)

            # From super.process_response
            # Delete any surplus cookies
            cookies_to_delete = getattr(request, 'cookies_to_delete', [])
            for cookie_key in cookies_to_delete:
                response.delete_cookie(cookie_key)

            if not request.user.is_authenticated():
                response.set_cookie(
                    cookie_key, cookie,
                    max_age=settings.OSCAR_BASKET_COOKIE_LIFETIME,
                    secure=settings.OSCAR_BASKET_COOKIE_SECURE, httponly=True)
            return response
        else:
            return super(
                ApiBasketMiddleWare, self).process_response(request, response)
 ```

Do you think it's a viable way?

**Comment by specialunderwear** [comment]
Please make a pull request and we will review it.
Could be that something changed in oscar, I think the point of
```
    def process_response(self, request, response):
        if self.is_api_request(request) and hasattr(request, 'user'):
            # at this point we are sure a basket can be found in the session,
            # because it is enforced in process_request.
            # We just have to make sure it is stored as a cookie, because it
            # could have been created by oscarapi.
            cookie_key = self.get_cookie_key(request)
            basket = get_basket(request)
            request.COOKIES[cookie_key] = self.get_basket_hash(basket.id)
```

is that the super call can find the basket or something. But the way it looks now, is that it prevents the cookie from being written because the super call thinks the cookie is allready there.

**Pull request merged**
