### PR TITLE
some work from @KuwaitNET

### PR DESCRIPTION
**Pull request by Bashar**
Wanted to have this to be reviewed and feedback by Oscar experts ? :)

@mbertheau @codeinthehole @maikhoepfel its all yours for feedback and reviews

@alexanderkuwaitnet work

### CODE REVIEW

**Comment by Bashar** [comment]
@ecugol @jab3z to stay in the loop

**Comment by specialunderwear** [comment]
Hi, unfortunately this pull request needs rebasing before it can be reviewed. In the process, you might find that some of the issues addressed in this pull request, have allready been solved in a different manner.

**Comment by maerteijn** [comment]
@Bashar I see that you added some serializers and views which don't exist yet in oscarapi (which could be useful). However, a lot changed already in the meanwhile (see also: https://pypi.python.org/pypi/django-oscar-api/1.0.3). So if there are some things left which you feel that should be in the api, could you please rebase (and review) your pull request?

**Comment by maerteijn** [comment]
I close this pull request due to almost 2 years of no response from KuwaitNET.

**Comment by SalahAdDin** [comment]
@Bashar  Hey man!

**Comment by Bashar** [comment]
my apologies, I weren't getting notifications on PRs, just responded to all my old notifications, my bad :sweat_smile: 

will review and submit newer PR if still needed, since a lot changed since then :)

**Pull request closed without merging**
