### PR TITLE
Add python 3 support and testing

### PR DESCRIPTION
**Pull request by bufke**
NOT READY FOR MERGE YET - wait for travis tests.

### CODE REVIEW

**Comment by bufke** [comment]
Fixes #50

**Comment by bufke** [comment]
dj1.7 and python 3.5 don't work. I don't think 1.7 supports 3.5. I think we can just exclude it. Looking up syntax now.

**Comment by maerteijn** [comment]
@bufke  See also the matrix of django-oscar itself: https://travis-ci.org/django-oscar/django-oscar/
Seems like 3.3 and 3.4 are working fine, and 3.5 is also not working with django-oscar ....

**Comment by bufke** [comment]
Tests are passing. Ok to merge once you review. Seems like 3.5 isn't an issue with these tests. Leave it as is?

**Comment by maerteijn** [comment]
I also tested manually and it all looks good... almost to good to be true :) In the end not so much work to support python3.5, nice job!

@specialunderwear Could you take a look as well before we merge it into master?

**Comment by maerteijn** [comment]
specialunderwear thinks it's good, so I'll merge it and tag a new release soon

**Pull request merged**
