### PR TITLE
Stay away from core apps

### PR DESCRIPTION
**Pull request by specialunderwear**
This pull request removes the basket app override and replaces it with functions that operate on baskets.

### CODE REVIEW

**Comment by mvantellingen** [comment]
Looks good! :-)

**Comment by maikhoepfel** [comment]
\o/ Lovely!

**Comment by mvantellingen** [comment]
Just looking through it some more, it seems that basket.managers can be removed?

**Comment by specialunderwear** [comment]
If you say so ...






Most of the time, the managers are obsolete.

**Pull request merged**
