### PR TITLE
Replace urls with paths

### PR DESCRIPTION
**Pull request by Andruten**
- Removed url in favour of path and re_path.
- CountryDetail's url regex only accepts two caracters for resolving

### CODE REVIEW

**Comment by specialunderwear** [comment]
so this PR will be merged AFTER the others are merged, so that can take a while.

**Comment by specialunderwear** [comment]
The tests are all failing, could you fix that?

**Comment by Andruten** [comment]
sure!

**Comment by Andruten** [comment]
Test are passing now 🙂

**Comment by maerteijn** [comment]
This will be  merged when we drop Django 1.11 support

**Comment by specialunderwear** [comment]
Hi, can you change this pull request to land on the master branch now, because the writable branch has been merged. This would then also need rebasing.

**Comment by Andruten** [comment]
I've created a new PR for this. #172

**Pull request closed without merging**
