### PR TITLE
Fix category slug always required

### PR DESCRIPTION
**Pull request by farooqaaa**
I have also added a test now.

### CODE REVIEW

**Comment by maerteijn** [comment]
The linting checker in travis fails, so I guess you have to run `make black` to fix that. You can run the linter yourself locally with `make lint`.

I remember you also wanted to fix this slug field for products as well right? Can you add that too?

**Comment by farooqaaa** [comment]
> I remember you also wanted to fix this slug field for products as well right? Can you add that too?

No, that's no longer needed. If you don't send a slug, it's created automatically.

**Comment by maerteijn** [comment]
Hi @farooqaaa Could you still fix the linting errors so I can merge this PR? Thank you!

**Comment by farooqaaa** [comment]
Hi @maerteijn Sorry for the delay. Linting errors are fixed now.

**Comment by maerteijn** [comment]
@farooqaaa Now the tests do not pass, [could you update the failing test](https://travis-ci.org/github/django-oscar/django-oscar-api/builds/738945435)?

**Comment by farooqaaa** [comment]
Done. Sorry! I don't have a dedicated environment for this repo so that's why it was a bit messy.

**Pull request merged**
